models/machine.py
import pandas as pd
import pickle
from sklearn.calibration import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# 1. Carregar os Dados
df = pd.read_csv('datasets/iris_data.csv')
#print(df.head())

# 2. Separar Características e Rótulos
# Selecionar colunas de características e rótulo
x = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']].values
y = df['variety'].values


# 3. Codificar Rótulos Categóricos
le = LabelEncoder()
y = le.fit_transform(y)
print(y)


# 4. Dividir os Dados
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Criar e treinar o modelo
sv = SVC(kernel='linear')
sv.fit(X_train, y_train)

# Salvar o modelo treinado
pickle.dump(sv, open('iris.pkl', 'wb'))

# Opcional: Exibir as primeiras linhas para verificar a preparação
print(df.head())

controllers/route.py
import pickle
from flask import redirect, request, url_for, Blueprint, render_template
import numpy as np

# Carregando o modelo
model = pickle.load(open('iris.pkl', 'rb'))

# Criando o Blueprint
app_blueprint = Blueprint('app', __name__)

# Rota raiz que redireciona para a página principal
@app_blueprint.route('/')
def root():
    return redirect(url_for('app.home'))

# Rota para a página principal
@app_blueprint.route('/IrisDataWeb/home')
def home():
    return render_template('index.html')

# Rota para a página de entrada do programa
@app_blueprint.route('/IrisDataWeb/home/program', methods=['GET'])
def program():
    return render_template('main.html')

# Rota para fazer a previsão usando o modelo
@app_blueprint.route('/IrisDataWeb/home/program/predict', methods=['POST'])
def predict():
    try:
        # Coleta dos dados do formulário com validação
        data1 = request.form.get('a', type=float)
        data2 = request.form.get('b', type=float)
        data3 = request.form.get('c', type=float)
        data4 = request.form.get('d', type=float)

        # Verificando se todos os dados foram fornecidos e são válidos
        if None in [data1, data2, data3, data4]:
            raise ValueError("Todos os dados do formulário devem ser fornecidos e devem ser números.")

        # Criando o array de entrada para o modelo
        arr = np.array([[data1, data2, data3, data4]])

        # Fazendo a previsão
        pred = model.predict(arr)[0]

        # Renderizando a página com a previsão
        return render_template('main.html', data=pred)

    except ValueError as ve:
        # Em caso de erro de valor, retornar a página com uma mensagem de erro específica
        return render_template('main.html', error=str(ve))
    except Exception as e:
        # Capturando outros tipos de exceções
        return render_template('main.html', error="Ocorreu um erro durante o processamento: " + str(e))

main.py
from flask import Flask
from controllers.route import app_blueprint

app = Flask(__name__)

# Registra o Blueprint
app.register_blueprint(app_blueprint)

# Executa a aplicação Flask
if __name__ == '__main__':
    # Configura para escutar no IP e porta desejados
    app.run(host='127.0.0.1', port=5000, debug=True)

routes/home.py
from flask import Flask, redirect
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def root():
    return redirect('/home')

@home_route.route('/home')
def home():
    return render_template('index.html')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/logo.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
    <title>Welcome to IrisDataWeb</title>
</head>
<body>
    <img class="plano-de-fundo" src="{{ url_for('static', filename='images/Irishome.jpg') }}">

    <div class="container">
        <header>
            <h2 class="title-page">Welcome to IrisDataWeb</h2>
        </header>
        <div id="logo-homer">
            <img id="logo" src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo do IrisDataWeb">
        </div>
        <div class="text">
            <p>Este projeto, intitulado IrisDataWeb, foi criado com o objetivo de explorar e aplicar meus conhecimentos em machine learning 
                integrados a uma interface web. 
                A ideia principal foi desenvolver uma aplicação 
                prática que utiliza modelos de aprendizado de máquina, como o famoso dataset Iris,
                para oferecer previsões de maneira interativa e acessível através de um ambiente online.</p>
        </div>
        <div class="gatways">
            <div class="main">
                <a href="{{ url_for('app.program') }}" class="button">Enter</a>
               
            </div>
        </div>
    </div>
</body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/logo.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
    <title>IrisDataWeb - Inputs</title>
</head>
<body>
    <img class="plano-de-fundo" src="{{ url_for('static', filename='images/Irishome.jpg') }}">

    <div class="container-inputs">
        <div id="header-inputs">
            <h3 class="title-page">IrisDataWeb</h3>
            <p></p>
        </div>
        
        <form method="POST" action="{{ url_for('app.predict') }}">
            <div class="input">
                <label for="comprimentoSepala">Comprimento da sépala (em centímetros):</label>
                <input type="number" id="comprimentoSepala" name="a" step="0.1" placeholder="Digite o comprimento da sépala" required>
            </div>
        
            <div class="input">
                <label for="larguraSepala">Largura da sépala (em centímetros):</label>
                <input type="number" id="larguraSepala" name="b" step="0.1" placeholder="Digite a largura da sépala" required>
            </div>
        
            <div class="input">
                <label for="comprimentoPetala">Comprimento da pétala (em centímetros):</label>
                <input type="number" id="comprimentoPetala" name="c" step="0.1" placeholder="Digite o comprimento da pétala" required>
            </div>

            <div class="input">
                <label for="larguraPetala">Largura da pétala (em centímetros):</label>
                <input type="number" id="larguraPetala" name="d" step="0.1" placeholder="Digite a largura da pétala" required>
            </div>
            <div class="gatways">
                <div class="main">
                    <button type="submit">Prever</button>
                </div>
            </div>
        </form>
        
        <div class="output">
            <h1>PREVISÃO:</h1>
            
            {% if data is not none %}
                {% if data == 0 %}
                    <img src="{{ url_for('static', filename='images/Iris-setosa.png') }}" alt="Iris-setosa">
                    <h2>Iris-setosa</h2>

                {% elif data == 1 %}
                    <img src="{{ url_for('static', filename='images/Iris-versicolor.png') }}" alt="Iris-versicolor">
                    <h2>Iris-versicolor</h2>
                    
                {% elif data == 2 %}
                    <img src="{{ url_for('static', filename='images/Iris-virginica.png') }}" alt="Iris-virginica">
                    <h2>Iris-virginica</h2>
                {% endif %}
            {% endif %}
        </div>
    </div>
</body>
</html>